export type Session = {
  id: string;
  game: BoardGame | null;
  date: Date;
  players: string[];
};

export type BoardGame = {
  id: string;
  title: string;
  designer: string;
  yearPublished: number;
  minPlayers: number;
  maxPlayers: number;
  playTimeMinutes: number;
  minAge: number;
  complexity: number;
  rating: number;
  categories: string[];
  available: boolean;
};

export const boardGames: BoardGame[] = [
  {
    id: '1',
    title: 'Catan',
    designer: 'Klaus Teuber',
    yearPublished: 1995,
    minPlayers: 3,
    maxPlayers: 4,
    playTimeMinutes: 90,
    minAge: 10,
    complexity: 2.3,
    rating: 7.1,
    categories: ['Strategy', 'Negotiation', 'Economic'],
    available: true,
  },
  {
    id: '2',
    title: 'Carcassonne',
    designer: 'Klaus-Jürgen Wrede',
    yearPublished: 2000,
    minPlayers: 2,
    maxPlayers: 5,
    playTimeMinutes: 45,
    minAge: 7,
    complexity: 1.9,
    rating: 7.4,
    categories: ['Family', 'Tile Placement'],
    available: true,
  },
  {
    id: '3',
    title: 'Pandemic',
    designer: 'Matt Leacock',
    yearPublished: 2008,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 45,
    minAge: 8,
    complexity: 2.4,
    rating: 7.5,
    categories: ['Cooperative', 'Strategy'],
    available: true,
  },
  {
    id: '4',
    title: 'Ticket to Ride',
    designer: 'Alan R. Moon',
    yearPublished: 2004,
    minPlayers: 2,
    maxPlayers: 5,
    playTimeMinutes: 60,
    minAge: 8,
    complexity: 1.8,
    rating: 7.4,
    categories: ['Family', 'Route Building'],
    available: false,
  },
  {
    id: '5',
    title: '7 Wonders',
    designer: 'Antoine Bauza',
    yearPublished: 2010,
    minPlayers: 3,
    maxPlayers: 7,
    playTimeMinutes: 30,
    minAge: 10,
    complexity: 2.3,
    rating: 7.7,
    categories: ['Card Drafting', 'Civilization'],
    available: true,
  },
  {
    id: '6',
    title: 'Azul',
    designer: 'Michael Kiesling',
    yearPublished: 2017,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 40,
    minAge: 8,
    complexity: 1.8,
    rating: 7.8,
    categories: ['Abstract', 'Tile Placement'],
    available: true,
  },
  {
    id: '7',
    title: 'Wingspan',
    designer: 'Elizabeth Hargrave',
    yearPublished: 2019,
    minPlayers: 1,
    maxPlayers: 5,
    playTimeMinutes: 70,
    minAge: 10,
    complexity: 2.5,
    rating: 8.1,
    categories: ['Engine Building', 'Card Game'],
    available: true,
  },
  {
    id: '8',
    title: 'Terraforming Mars',
    designer: 'Jacob Fryxelius',
    yearPublished: 2016,
    minPlayers: 1,
    maxPlayers: 5,
    playTimeMinutes: 120,
    minAge: 12,
    complexity: 3.3,
    rating: 8.4,
    categories: ['Engine Building', 'Strategy', 'Science Fiction'],
    available: false,
  },
  {
    id: '9',
    title: 'Gloomhaven',
    designer: 'Isaac Childres',
    yearPublished: 2017,
    minPlayers: 1,
    maxPlayers: 4,
    playTimeMinutes: 120,
    minAge: 14,
    complexity: 3.9,
    rating: 8.6,
    categories: ['Campaign', 'Cooperative', 'Dungeon Crawl'],
    available: true,
  },
  {
    id: '10',
    title: 'Brass: Birmingham',
    designer: 'Martin Wallace',
    yearPublished: 2018,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 120,
    minAge: 14,
    complexity: 3.9,
    rating: 8.6,
    categories: ['Economic', 'Network Building'],
    available: true,
  },
  {
    id: '11',
    title: 'Spirit Island',
    designer: 'R. Eric Reuss',
    yearPublished: 2017,
    minPlayers: 1,
    maxPlayers: 4,
    playTimeMinutes: 120,
    minAge: 13,
    complexity: 4.1,
    rating: 8.4,
    categories: ['Cooperative', 'Area Control'],
    available: false,
  },
  {
    id: '12',
    title: 'Root',
    designer: 'Cole Wehrle',
    yearPublished: 2018,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 90,
    minAge: 10,
    complexity: 3.8,
    rating: 8.0,
    categories: ['Area Control', 'Asymmetric', 'Wargame'],
    available: true,
  },
  {
    id: '13',
    title: 'Codenames',
    designer: 'Vlaada Chvátil',
    yearPublished: 2015,
    minPlayers: 2,
    maxPlayers: 8,
    playTimeMinutes: 15,
    minAge: 14,
    complexity: 1.3,
    rating: 7.5,
    categories: ['Party', 'Word Game', 'Deduction'],
    available: true,
  },
  {
    id: '14',
    title: 'The Crew: The Quest for Planet Nine',
    designer: 'Thomas Sing',
    yearPublished: 2019,
    minPlayers: 2,
    maxPlayers: 5,
    playTimeMinutes: 20,
    minAge: 10,
    complexity: 2.0,
    rating: 8.0,
    categories: ['Cooperative', 'Card Game', 'Trick Taking'],
    available: true,
  },
  {
    id: '15',
    title: 'Splendor',
    designer: 'Marc André',
    yearPublished: 2014,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 30,
    minAge: 10,
    complexity: 1.8,
    rating: 7.4,
    categories: ['Card Drafting', 'Economic'],
    available: false,
  },
  {
    id: '16',
    title: 'Dixit',
    designer: 'Jean-Louis Roubira',
    yearPublished: 2008,
    minPlayers: 3,
    maxPlayers: 6,
    playTimeMinutes: 30,
    minAge: 8,
    complexity: 1.2,
    rating: 7.3,
    categories: ['Party', 'Storytelling'],
    available: true,
  },
  {
    id: '17',
    title: 'Scythe',
    designer: 'Jamey Stegmaier',
    yearPublished: 2016,
    minPlayers: 1,
    maxPlayers: 5,
    playTimeMinutes: 115,
    minAge: 14,
    complexity: 3.4,
    rating: 8.2,
    categories: ['Area Control', 'Engine Building'],
    available: true,
  },
  {
    id: '18',
    title: 'Everdell',
    designer: 'James A. Wilson',
    yearPublished: 2018,
    minPlayers: 1,
    maxPlayers: 4,
    playTimeMinutes: 80,
    minAge: 13,
    complexity: 2.8,
    rating: 8.0,
    categories: ['Worker Placement', 'Card Game'],
    available: true,
  },
  {
    id: '19',
    title: 'Agricola',
    designer: 'Uwe Rosenberg',
    yearPublished: 2007,
    minPlayers: 1,
    maxPlayers: 5,
    playTimeMinutes: 120,
    minAge: 12,
    complexity: 3.6,
    rating: 7.9,
    categories: ['Worker Placement', 'Farming'],
    available: false,
  },
  {
    id: '20',
    title: 'Cascadia',
    designer: 'Randy Flynn',
    yearPublished: 2021,
    minPlayers: 1,
    maxPlayers: 4,
    playTimeMinutes: 45,
    minAge: 10,
    complexity: 1.9,
    rating: 7.9,
    categories: ['Family', 'Tile Placement', 'Puzzle'],
    available: true,
  },
];
