packages:
  - 'apps/0[1-8]-*'
  - 'apps/0[1-8]-*/*'
  - 'apps/00-side-projects/*'
  - 'bootcamp/*'
  - 'bootcamp/*/*'
  - 'bootcamp/*/*/*'
  - 'bootcamp/*/*/*/*'
  - 'packages/*'
  - 'playgrounds/*'
allowBuilds:
  esbuild: true
