import type { Request, Response } from 'express';
import fs from 'node:fs/promises';
import path from 'node:path';
import {
  loadPosts,
  getPostBySlug,
  addPost,
  updatePost,
  deletePost,
  type Post,
} from '../../models/post.model.ts';
import {
  getSlugParam,
  sanitizePostContent,
  formatDate,
} from '../../utils/utils.ts';

const UPLOAD_DIR = path.join(process.cwd(), 'src/assets/img/post-bg');

/**
 * Helper to delete an image file safely from disk
 */
async function removeImageFromDisk(filename?: string): Promise<void> {
  if (!filename) return;
  const filePath = path.join(UPLOAD_DIR, filename);
  try {
    await fs.unlink(filePath);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') {
      console.error(`Failed to delete image file (${filename}):`, err);
    }
  }
}

export async function getAdminDashboard(
  _req: Request,
  res: Response,
): Promise<void> {
  const posts = await loadPosts();
  const view = posts.map((post) => ({
    ...post,
    createdAt: formatDate(post.createdAt),
  }));
  res.render('admin/dashboard.njk', { posts: view });
}

export async function getNewPostForm(
  _req: Request,
  res: Response,
): Promise<void> {
  res.render('admin/post-create.njk');
}

export async function createPost(req: Request, res: Response): Promise<void> {
  // Safely fallback to {} to prevent crashing if req.body is undefined
  const { title, author, teaser, content } = req.body || {};

  if (!title || !author) {
    res.status(400).send('Title and author are required');
    return;
  }

  // Extract the filename generated by Multer if an image was uploaded
  const imageFilename = req.file ? req.file.filename : '';

  const newPost: Post = {
    title,
    image: imageFilename,
    author,
    teaser,
    content: sanitizePostContent(content),
    createdAt: Math.floor(Date.now() / 1000),
  };

  try {
    await addPost(newPost);
    res.redirect('/admin');
  } catch (err) {
    res.status(400).render('admin/post-create.njk', {
      error: (err as Error).message,
      post: newPost,
    });
  }
}

export async function getEditPostForm(
  req: Request,
  res: Response,
): Promise<void> {
  const slug = getSlugParam(req.params['slug']);

  if (!slug) {
    res.status(400).send('Invalid slug');
    return;
  }

  const post = await getPostBySlug(slug);

  if (!post) {
    res.status(404).render('public/404.njk');
    return;
  }

  res.render('admin/post-edit.njk', {
    post: { ...post, createdAt: formatDate(post.createdAt) },
  });
}

export async function updatePostHandler(
  req: Request,
  res: Response,
): Promise<void> {
  const slug = getSlugParam(req.params['slug']);

  if (!slug) {
    res.status(400).send('Invalid slug');
    return;
  }

  const existingPost = await getPostBySlug(slug);

  if (!existingPost) {
    res.status(404).render('public/404.njk');
    return;
  }

  const { title, author, teaser, content } = req.body || {};

  if (!title || !author) {
    res.status(400).send('Title and author are required');
    return;
  }

  let imageFilename = existingPost.image;

  // If a new file was uploaded, delete the old file and use the new filename
  if (req.file) {
    await removeImageFromDisk(existingPost.image);
    imageFilename = req.file.filename;
  }

  const changes: Partial<Post> = {
    title,
    image: imageFilename,
    author,
    teaser,
    content: sanitizePostContent(content),
  };

  try {
    await updatePost(slug, changes);
    res.redirect('/admin');
  } catch (err) {
    res.status(500).render('admin/post-edit.njk', {
      error: (err as Error).message,
      post: { ...existingPost, ...changes },
    });
  }
}

export async function deletePostHandler(
  req: Request,
  res: Response,
): Promise<void> {
  const slug = getSlugParam(req.params['slug']);

  if (!slug) {
    res.status(400).send('Invalid slug');
    return;
  }

  try {
    const post = await getPostBySlug(slug);

    // Delete associated image file from disk before removing DB entry
    if (post && post.image) {
      await removeImageFromDisk(post.image);
    }

    await deletePost(slug);
  } catch (err) {
    console.error(`Failed to delete post "${slug}":`, err);
  }

  res.redirect('/admin');
}
