import type { Request, Response } from 'express';
import fs from 'node:fs/promises';
import path from 'node:path';
import type { PostService } from '../../services/PostService.ts';
import type { Post } from '../../entities/Post.ts';
import { getSlugParam, formatDate } from '../../utils/utils.ts';

const UPLOAD_DIR = path.join(process.cwd(), 'src/assets/img/post-bg');

export class AdminPostController {
  constructor(private readonly postService: PostService) {}

  /**
   * Helper to delete an image file safely from disk. Stays private here for
   * now — it moves to ImageStorageService in Phase 5, not this phase.
   *
   * `filename` ultimately comes from the `posting.image` column, which the
   * JSON API (ApiPostController) can also write to — so it isn't guaranteed
   * to be a bare filename. Strip any directory components and re-confirm the
   * resolved path still lives inside UPLOAD_DIR before deleting anything, so
   * a value like `../../../../etc/passwd` can't unlink outside the upload
   * directory.
   */
  private async removeImageFromDisk(filename?: string): Promise<void> {
    if (!filename) return;

    const safeName = path.basename(filename);
    const filePath = path.resolve(UPLOAD_DIR, safeName);
    const resolvedUploadDir = path.resolve(UPLOAD_DIR) + path.sep;

    if (!filePath.startsWith(resolvedUploadDir)) {
      console.error(`Refused to delete image outside upload dir: ${filename}`);
      return;
    }

    try {
      await fs.unlink(filePath);
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code !== 'ENOENT') {
        console.error(`Failed to delete image file (${filename}):`, err);
      }
    }
  }

  getAdminDashboard = async (_req: Request, res: Response): Promise<void> => {
    const posts = await this.postService.loadPosts();
    const view = posts.map((post) => ({
      ...post,
      createdAt: formatDate(post.createdAt),
    }));
    res.render('admin/dashboard.njk', { posts: view });
  };

  getNewPostForm = async (_req: Request, res: Response): Promise<void> => {
    res.render('admin/post-create.njk');
  };

  createPost = async (req: Request, res: Response): Promise<void> => {
    // Safely fallback to {} to prevent crashing if req.body is undefined
    const { title, author, teaser, content } = req.body || {};

    if (!title || !author) {
      res.status(400).send('Title and author are required');
      return;
    }

    // Extract the filename generated by Multer if an image was uploaded
    const imageFilename = req.file ? req.file.filename : '';

    // Content is sanitized inside postService.createPost — no need to do it
    // here too.
    const newPost: Post = {
      title,
      image: imageFilename,
      author,
      teaser,
      content,
      createdAt: Math.floor(Date.now() / 1000),
    };

    try {
      await this.postService.createPost(newPost);
      res.redirect('/admin');
    } catch (err) {
      res.status(400).render('admin/post-create.njk', {
        error: (err as Error).message,
        post: newPost,
      });
    }
  };

  getEditPostForm = async (req: Request, res: Response): Promise<void> => {
    const slug = getSlugParam(req.params['slug']);

    if (!slug) {
      res.status(400).send('Invalid slug');
      return;
    }

    const post = await this.postService.getPostBySlug(slug);

    if (!post) {
      res.status(404).render('public/404.njk');
      return;
    }

    res.render('admin/post-edit.njk', {
      post: { ...post, createdAt: formatDate(post.createdAt) },
    });
  };

  updatePostHandler = async (req: Request, res: Response): Promise<void> => {
    const slug = getSlugParam(req.params['slug']);

    if (!slug) {
      res.status(400).send('Invalid slug');
      return;
    }

    const existingPost = await this.postService.getPostBySlug(slug);

    if (!existingPost) {
      res.status(404).render('public/404.njk');
      return;
    }

    const { title, author, teaser, content } = req.body || {};

    if (!title || !author) {
      res.status(400).send('Title and author are required');
      return;
    }

    let imageFilename = existingPost.image;

    // If a new file was uploaded, delete the old file and use the new filename
    if (req.file) {
      await this.removeImageFromDisk(existingPost.image);
      imageFilename = req.file.filename;
    }

    // Content is sanitized inside postService.updatePost — no need to do it
    // here too.
    const changes: Partial<Post> = {
      title,
      image: imageFilename,
      author,
      teaser,
      content,
    };

    try {
      await this.postService.updatePost(slug, changes);
      res.redirect('/admin');
    } catch (err) {
      res.status(500).render('admin/post-edit.njk', {
        error: (err as Error).message,
        post: { ...existingPost, ...changes },
      });
    }
  };

  deletePostHandler = async (req: Request, res: Response): Promise<void> => {
    const slug = getSlugParam(req.params['slug']);

    if (!slug) {
      res.status(400).send('Invalid slug');
      return;
    }

    try {
      const post = await this.postService.getPostBySlug(slug);

      // Delete associated image file from disk before removing DB entry
      if (post && post.image) {
        await this.removeImageFromDisk(post.image);
      }

      await this.postService.deletePost(slug);
    } catch (err) {
      console.error(`Failed to delete post "${slug}":`, err);
    }

    res.redirect('/admin');
  };
}
